# Generated by Django 6.0.2 on 2026-05-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('nutritionist', 'Nutritionist'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
