# Generated by Django 6.0.2 on 2026-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription',
            field=models.BooleanField(default=False, help_text='True if user has an active subscription'),
        ),
    ]
