# Generated by Django 6.0.2 on 2026-05-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_userprofile_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('subscribed', 'Subscribed'), ('nutritionist', 'Nutritionist'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
