# Generated by Django 6.0.2 on 2026-05-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
