# Generated by Django 6.0.2 on 2026-05-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_message_options_rename_message_message_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='read',
        ),
    ]
