# Generated by Django 6.0.2 on 2026-05-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_message_options_rename_is_read_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ban_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
