# Generated by Django 6.0.2 on 2026-05-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_userprofile_ban_reason_userprofile_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
