# Generated by Django 6.0.2 on 2026-05-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_blog_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='meal_plan',
            field=models.CharField(choices=[('weight-loss', 'Weight Loss Plan'), ('muscle-gain', 'Muscle Gain Plan'), ('maintenance', 'Maintenance Plan')], default='maintenance', max_length=50),
        ),
    ]
