# Generated by Django 6.0.2 on 2026-05-17 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_userprofile_meal_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=20)),
                ('meal_name', models.CharField(max_length=255)),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.FloatField(blank=True, default=0)),
                ('carbs', models.FloatField(blank=True, default=0)),
                ('fat', models.FloatField(blank=True, default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meal_type', 'created_at'],
            },
        ),
    ]
