# Generated by Django 6.0.2 on 2026-05-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_mealplanitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='meal_plan',
        ),
        migrations.DeleteModel(
            name='MealPlanItem',
        ),
    ]
